version: 2.1
jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline # gets the project dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      - run: mvn package
  publish_image_to_quay:
    docker:
      - image: circleci/openjdk:11-jdk-buster
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64
      IMAGE_PREFIX: ghcr.io/lht
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.7"
      - run:
          name: Install buildx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            # Run binfmt
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run: echo "$GHCR_TOKEN" | docker login https://ghcr.io -u lht --password-stdin
      - run: |
          docker context create ctx
          docker buildx create ctx --name builder --use
          if [[ -n "$CIRCLE_TAG" ]]; then
            docker buildx build \
              --platform "$BUILDX_PLATFORMS" \
              -t $IMAGE_PREFIX/cloudwatch-exporter:"${CIRCLE_TAG}" \
              -t $IMAGE_PREFIX/cloudwatch-exporter:latest --push .
          else
            docker buildx build \
              --platform "$BUILDX_PLATFORMS" \
              -t $IMAGE_PREFIX/cloudwatch-exporter:latest --push .
          fi
      - run: docker images
workflows:
  version: 2
  cloudwatch_exporter:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish_image_to_quay:
#         context: org-context
          requires:
            - build
          filters:
            branches:
              only: test
            tags:
              only: /.*/
